--- #YAML:1.0
name: Config-Natural
version: 0.99_05
license: perl
distribution_type: module
requires:
  Carp: 0
  File::Spec: 0
  FileHandle: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Config::Natural:
    file: lib/Config/Natural.pm
    version: 0.99_05
generated_by: Module::Build version 0.19_05
