--- #YAML:1.0
name: Config-Natural
version: 0.97
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Config::Natural:
    file: lib/Config/Natural.pm
    version: 0.97
generated_by: Module::Build version 0.19_05
